version: '3'
services:
  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
  auth-service:
    build: ./services/auth-service
    ports:
      - "4001:4001"
  user-service:
    build: ./services/user-service
    ports:
      - "4002:4002"
